export const BUDGET_COLORS = [
  { name: 'Green',     value: '#277C78' },
  { name: 'Yellow',    value: '#F2CDAC' },
  { name: 'Cyan',      value: '#82C9D7' },
  { name: 'Navy',      value: '#626070' },
  { name: 'Red',       value: '#C94736' },
  { name: 'Purple',    value: '#826CB0' },
  { name: 'Turquoise', value: '#597C7C' },
  { name: 'Brown',     value: '#93674F' },
  { name: 'Magenta',   value: '#934F6F' },
  { name: 'Blue',      value: '#3F82B2' },
  { name: 'Grey',      value: '#97A0AC' },
  { name: 'Army',      value: '#7F9161' },
  { name: 'Pink',      value: '#AF81BA' },
  { name: 'Gold',      value: '#CAB361' },
  { name: 'Orange',    value: '#BE6C49' },
] as const;

export const BUDGET_CATEGORIES = [
  'Entertainment',
  'Bills',
  'Groceries',
  'Dining Out',
  'Transportation',
  'Personal Care',
  'Education',
  'Lifestyle',
  'Shopping',
  'General',
] as const;
